### ISSUE TITLE
[BUG/FEATURE REQUEST] Change some header fields

### ISSUE THREAD

**Issue by herbnilson** [nbenm/ImapNote2#13]
Hello,

Right now Imapnotes2 creates kind of "special"  „from“-fields and  "date"- fields that break a third party web notes app i would like to use.

Do you think it is an option to change the „from“ and „date“ field to something more „standard“?

For example like this:

from: From: "myadress@somewhere.com" <ImapNotes2>
To: From: myadress@somewhere.com

and the Date-Field:

 from: Wed, 4 Nov 2015 22:38:30 +0100 (GMT+01:00)
to: Wed, 4 Nov 2015 22:36:32 +0100

This way Imapnotes2 would  be closer to the Apple Notes as well.

Thanks for considering the request
regards hb

---

Maybe the following comparison of the same note (same content) illustrates it.

**1. created with Notes App (OSX Yosemite)**

`From: redacted@somemail.com`
`X-Uniform-Type-Identifier: com.apple.mail-note`
`Content-Type: text/html;`
`charset=us-ascii`
`Content-Transfer-Encoding: 7bit`
`Mime-Version: 1.0 (Mac OS X Notes 3.3 \(353\))`
`Date: Wed, 4 Nov 2015 22:36:32 +0100`
`X-Mail-Created-Date: Wed, 4 Nov 2015 22:36:27 +0100`
`Subject: just a few words in a note`
`X-Universally-Unique-Identifier: C95C4B45-ECDB-4C8A-890C-AC663B8BC802`
`Message-Id: <65D2A5B7-26D7-42A8-8B10-E59D7EEC813A@xyz.abc>`

`<html><head></head><body>just a few words in a note</body></html>`

**2. created with imapnotes2**

`Date: Wed, 4 Nov 2015 22:38:30 +0100 (GMT+01:00)`
`From: "redacted@somemail.com" <ImapNotes2>`
`Message-ID: <386221405.0.1446673110889.JavaMail.root@localhost>`
`Subject: just a few words in a note`
`MIME-Version: 1.0`
`Content-Type: text/html; charset=utf-8`
`Content-Transfer-Encoding: 7bit`
`X-Uniform-Type-Identifier: com.apple.mail-note`
`X-Universally-Unique-Identifier: 8d359de7-20c4-4d26-84a8-53e5ea2727fa`

`<html><head></head><body><div>just a few words in a note</div>`
`</body></html>`

**3. created with Notes App (El Capitan)**

`From: redacted@somemail.com`
`X-Uniform-Type-Identifier: com.apple.mail-note`
`Content-Type: text/html;`
    `charset=us-ascii`
`Content-Transfer-Encoding: 7bit`
`Mime-Version: 1.0 (Mac OS X Notes 4.2 \(549.10.1\))`
`Date: Wed, 16 Dec 2015 20:00:03 +0100`
`X-Mail-Created-Date: Wed, 16 Dec 2015 20:00:00 +0100`
`Subject: just a few words in a note`
`X-Universally-Unique-Identifier: BCE4B03C-6234-4B36-86D8-D18D02CD491E`
`Message-Id: <3CEC5254-2F29-486B-9F63-10E883B92BCB@xyz.abc>`

`<html><head></head><body style="word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space;">just a few words in a note</body></html>`

**Comment by N0ury** [comment]
Hi herbnilson,

I have two questions
1 - I don't have the quotes in the From address, but I do have the <ImapNotes2> part
     are talking about the quotes or the <ImapNotes2> part?
     the <ImapNotes2> string can be removed, it's just informationnal
2 - Which web notes app are you talking about?

Regards

Noury

**Comment by N0ury** [comment]
Hi herbnilson,

I think your request is solved in V4.6.
Can you please check if it's ok

Regards

Noury

**Comment by herbnilson** [comment]
Hi Noury,
thank you  for the quick fix. V4.6. solved the issue.

Regards
hn

**Comment by herbnilson** [comment]
Hello Noury,

thank you for the quick fix and thank you for providing an imap note android app that can sync with any email provider and works with the apple notes app as well.

I just wrote a short note on github, because not all of the details are interesting for the public.

You are right, the quotes only showed up in the example i gave you (4th of November). Afterwards i didn’t see quotes, either.

The web app i was mentioning is <posteo.de/notes>  It works now. Thank you.

Can i reach you someplace else? Telegram, IRC, Signal … Or do you prefer the emails via github?

I have a few more questions regarding the Imapnotes2-App … 

Thx again

Best Regards

Niels

**Comment by N0ury** [comment]
Hi Niels,

You can write to nb@dagami.org it's my personal email address

Noury
