### ISSUE TITLE
[Feature Request] Availability on F-Droid

### ISSUE THREAD

**Issue by Mosrite** [nbenm/ImapNote2#14]
Since this app is open source, could it be made available on F-Droid? By this, it would be accessible more easily for people who try to avoid Google services and apps.
--> https://f-droid.org/

Thanks for considering my suggestion!

**Comment by N0ury** [comment]
@Mosrite The app is on f-droid now. Can you please tell me if this issue can be closed
Thanks

**Comment by Mosrite** [comment]
Yes, I found it on F-Droid. Thanks, I appreciate your effort!
