### ISSUE TITLE
Manual directory creation

### ISSUE THREAD

**Issue by ghost** [nbenm/ImapNote2#19]
Just installed ImapNote2 (version 4.9 , code 40) for the first time via f-droid , both on my tablet and phone.
Setup my account to my Courier IMAPS server on both devices , no errors.
Created a note , performed a sync but no note appears on the other device.
Checked the Maildir folder structure in the shell and no Notes folder , created it manually in my email client.
Sync'ed again in ImapNote2 , my test note disappeared , but now seeing a 'Last Sync' message in the black bar.
Created a new note , sync'ed , new note now appearing on other device.
Hope that helps.
This looks like a new application , Thanks!
Is it necessary to create the Notes folder manually or should this be automatic ?

**Comment by N0ury** [comment]
Hi Mark,

Thanks for your feedback.
The app doesn't create Notes directory. It is assumed it already exists on the server.
In the very early days, namespaces were not handled.
As a first step I think it can be easy to display a popup saying that no "Notes" folder was found.
As a second one, "Notes" folder would be automatically created.

Regards

**Comment by ghost** [comment]
Thanks for the explanation @nbenm , it was a little confusing that's all.
