### ISSUE TITLE
Add delete confirmation to avoid accidental delete

### ISSUE THREAD

**Issue by krasi-georgiev** [nbenm/ImapNote2#25]
I happened that few of my notes go deleted while the phone was in my pocket somehow.

Could you please add a confirmation on a note deletion.

**Comment by krasi-georgiev** [comment]
ar maybe move it on the other side of the screen so it is not next to the save button

**Comment by chrisgraham** [comment]
Implemented on my fork https://github.com/ocproducts/ImapNote2/commit/ffaa48c6d360c7c5164d41b27865b1bb01d122b1
