### ISSUE TITLE
Doesn't work with Yahoo IMAP.

### ISSUE THREAD

**Issue by kwhitefoot** [nbenm/ImapNote2#26]
The app silently failed to do anything although it does appear to successfully log in so I cloned the repository and ran it in Android Studio and saw that it failed in 

```
ImapNotes2Result ConnectToRemote() {
```

I modified a line to show the result in the log like this:

```
    if (res.returnCode != 0) {
        Log.d(TAG,"Connection problem !!!: " + res.returnCode+ " " + res.errorMessage + " " + res.notesFolder);
    }
```

and got this in the log (see the last line):

10-22 22:40:32.779 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 SSL_connect:ok exit in SSLOK  SSL negotiation finished successfully
10-22 22:40:32.779 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 info_callback ignored
10-22 22:40:32.779 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: doing handshake -- ret=1
10-22 22:40:32.779 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 NativeCrypto_SSL_get_certificate => NULL
10-22 22:40:32.782 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslRead buf=0x41dc9988 len=2048,timeo=0
10-22 22:40:32.833 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslWrite buf=0x41ecc3e8 len=23 write_timeout_millis=0
10-22 22:40:32.833 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslRead buf=0x41dc9988 len=2048,timeo=0
10-22 22:40:32.886 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslWrite buf=0x41ecc3e8 len=54 write_timeout_millis=0
10-22 22:40:32.887 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslRead buf=0x41dc9988 len=2048,timeo=0
10-22 22:40:33.647 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslWrite buf=0x41ecc3e8 len=15 write_timeout_millis=0
10-22 22:40:33.647 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslRead buf=0x41dc9988 len=2048,timeo=0
10-22 22:40:33.869 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslWrite buf=0x41ecc3e8 len=14 write_timeout_millis=0
10-22 22:40:33.870 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslRead buf=0x41dc9988 len=2048,timeo=0
10-22 22:40:34.089 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslWrite buf=0x41ecc3e8 len=31 write_timeout_millis=0
10-22 22:40:34.090 10169-24541/com.Pau.ImapNotes2 D/NativeCrypto: ssl=0x6212cf90 sslRead buf=0x41dc9988 len=2048,timeo=0
10-22 22:40:34.338 10169-24541/com.Pau.ImapNotes2 D/IN_SyncUtils: Cannot obtain UIDValidity
10-22 22:40:34.338 10169-24541/com.Pau.ImapNotes2 D/SyncAdapter: Connection problem !!!: -2 Cannot obtain UIDValidity null

**Comment by N0ury** [comment]
Hi,

I've just tried it. I didn't check Yahoo! for years.
They have changed their password policy.
apps are not allowed unless they are permitted in your account.
so you have to go to:
https://login.yahoo.com/account/security#other-apps
and explicitly permit "other applications to connect"
After that it worked for me.
But I'm not sure you have the same problem.
The message says you don't have a UIDValidity. Maybe it's a new and "empty" account. Try first to send a mail to this account. Don't forget to create a "Notes" folder too.

**Comment by kwhitefoot** [comment]
@nbenm Thanks for a quick response.  This account is one that I have been using for many, many years, and it is already set to allow 'insecure' access because I use Brandon Zehm's sendemail Perl script to send email through it from my Linux box via SMTP.  

Nonetheless, I'll double check to make sure it is working as it should.

Another thing, you said:  "Don't forget to create a "Notes" folder too."; but I tried my Hotmail (outlook.com) account and that worked straight away and the Notes folder was created for me.  The strange thing is that even though I can see the Notes folder in Thunderbird I can't see it in the Outlook web page.  Very strange.  I'll try creating one in the Yahoo account to see if it makes a difference.

**Comment by kwhitefoot** [comment]
@nbenm After creating the Notes folder in Yahoo it now works!
