### ISSUE TITLE
Not usable with the default fastmail settings

### ISSUE THREAD

**Issue by mbocode** [nbenm/ImapNote2#3]
When used with fastmail default settings, I get an error during the connection: `"INBOX" not found.`

Fastmail provides a workaround on their website to make this work:

> Alternate namespace. Some IMAP software (for example, Blackberry BIS, K9 Mail on Android or Apple Mail) has been known to have problems with the INBOX root folder path that FastMail uses. You can work around that by changing which port you use to access your mail. Change 993 to 992 and leave the Root folder/path blank.

Nerveless, it would be nice it works out of the box.

Cheers!

**Comment by N0ury** [comment]
Hi,

Sorry for this late response, I had much work to improve the app by making it using multiple accounts.

In v3.01, personnal namespace is detected. So you can use the app with Fastmail by accessing via port 993. It's no more necessary to use port 992.
I'm going to tell this to Fastmail too.

Thanks for your interest to ImapNotes2.

Regards

Noury
