### ISSUE TITLE
[Bug] "Password mode" for keyboard enabled when editing notes

### ISSUE THREAD

**Issue by Mosrite** [nbenm/ImapNote2#8]
Hello,

I'm using TouchPal keyboard, so i don't know if this is a general bug or specific to using ImapNote2 with TouchPal:
When creating or editing notes within the app the TouchPal keyboard is in "password mode". This means swiping, auto spell correction and word suggestions are disabled. I don't think this is necessary for notes.
Maybe this could be changed so that notes can be created and editing with full keyboard functionality?

Thanks in advance!

**Comment by Mosrite** [comment]
By the way, I just set up the app on my Samsung tablet running stock OS based on Android 5.0.2 with stock keyboard. It's the same: Swiping does not work, so the problem is not on TouchPal's site.

**Comment by capi** [comment]
Yes, noticed this as well.

And the hostname and username when editing accounts is a plain text field, causing auto-correction with SwiftKey while entering those information (which is especially cumbersome when entering a hostname :)).

**Comment by N0ury** [comment]
Please Mosrite,

Can you confirm issue can be closed ?

Thanks

Regards

**Comment by Mosrite** [comment]
Is there an up-to-date apk file available somewhere? I don't use Google Play, and the apk downloader (https://apps.evozi.com/apk-downloader/) constantly runs out of devices.

**Comment by capi** [comment]
@Mosrite I cannot provide one since I do not have the signature keys. But maybe @nbenm can build one, tag the current version and add it to the tag's download page here on Github.

**Comment by N0ury** [comment]
I’ve just tagged this version, and added apk to it.
@Martin, since it’s the first time I do this, can you please confirm it’s ok
Thanks

**Comment by Mosrite** [comment]
It's fixed now, thanks a lot!
